name: Creating screenshots of heroes power charts

on:
  push:
    #    paths:
    #      - 'content/heroBuilds.ts'
    branches:
      - feature/heroes-power-screenshots-git-action

jobs:
  create_screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Check out dota-react
        uses: actions/checkout@v4
        with:
          repository: dota-coach/dotaReact
          ref: feature/heroes-power-level
          token: ${{ secrets.GH_AUTH_TOKEN }}

      - name: Copy package-lock.json to package.json
        run: cp package-lock.json package.json

      - name: Install dependencies
        run: npm install

      - name: Change directory to submodules
        run: cd submodules

      - name: Update submodules
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
        run: |
          git config --global url."https://${GITHUB_TOKEN}:${GITHUB_TOKEN}@github.com/".insteadOf https://github.com/
          git submodule sync
          git submodule update --init --recursive

      - name: Change directory back to root
        run: cd ..

      - name: Run command to create hero power charts screenshots
        run: npm run heroes-power-charts-screenshots:create

      - name: Change directory to dota-brain
        run: cd dota-brain

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload file to S3
        run: |
          aws s3 cp src/scripts/heroesPowerLevelChartsScreenshots/out s3://${{ vars.AWS_S3_BUCKET }}/${{ vars.AWS_S3_PATH }}

      - name: Invalidate AWS CloudFront download.dotacoach.gg
        run: aws cloudfront create-invalidation --region us-east-1 --distribution-id ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION }} --paths ${{ vars.AWS_S3_PATH }}